### ISSUE TITLE
[Question] Memory requirement for loading a "dylib"

### ISSUE THREAD

**Issue by kaustavdm** [tyleo/sharedlib#8]
I was trying to hack around `dlopen` and then I found `sharedlib`. Looks like I finally found an answer to developing a plugin system for my application :-) So, first of all, thanks!

My requirement is kind of a classic use case for `sharedlib`. My [application](https://github.com/muktakosh/unicorn) will have multiple layers (protocols and APIs) of plugins, with the eventual goal of making these plugins composable. These plugins need to be loaded at runtime by the main binary (named `unicorn`), depending on runtime arguments and configuration.

The core application is written in Rust and, for now, all the plugins will be in Rust as well. I'm compiling them using `crate_type` as `dylib`. Each of these plugins expose a set of known symbols. They are stored in a known location, like this:

```
- plugins/
    -- libx.so
    -- liby.so
```

To make things simple, consider this example: When the main binary is run with `unicorn run x`, it loads `libx` with `Lib::new("plugins/libx.so")`, tries to find a function symbol called `run\0` and executes it.

Now, my question is, pardon the noobness: Will `sharedlib` load the entire `.so` file in memory when I try to load one of the plugins? So, if the `.so` file is 5MB in size, does that mean 5MB of memory is used to open the lib?

(Edit) P.S. AFAIK Dynamic loading is supposed to load the library in memory, get pointers, execute them and unload. My question is to know whether `sharedlib` does the same for the libraries it loads.

**Comment by tyleo** [comment]
The answer to this question is platform dependent. In other words: different operating systems will behave differently. For Linux, we are just calling `dlopen` with `RTLD_LAZY` so whatever your OS does with that is what's gonna happen. In general this means your library will be loaded into memory when `Lib::new()` is called, and unloaded from memory when all references to the `Lib` are lost. I imagine that you would get the most detailed information if you analyzed the memory usage of a sample application yourself by checking memory usage once before loading any `Lib`s, again after loading a `Lib`, and then one last time after unloading the `Lib`. Unfortunately, I have not done this test myself. You can find more information about what happens when these functions are called for your platform by searching Google or StackOverflow.

**Comment by kaustavdm** [comment]
Thanks @tyleo! That answers a good part of the things I want to know. I'll do a basic benchmark on my side and post it here.

**Comment by kaustavdm** [comment]
I have written a [demo for sharedlib](https://github.com/kaustavdm/rust-sharedlib-demo) in the meanwhile. I'll try and see what benchmark I can get out of this once I implement this in unicorn.

**Comment by tyleo** [comment]
This is amazing, thank you!

On another note: I originally wrote sharelib To assist with another project I am working on, graphy. I have two (currently undocumented) projects, graphy_dll, and graphy_module, which allow shared libraries to be loaded as plugins similarly to what you described above. I didn't mention it at first because it may be a bit heavyweight for what you are doing but if you are interested, I could elaborate.

In summary there is a modules folder which contains a json file describing the modules, and one folder for each module. Each module has an additional json which contains a dll path (usually just the current folder) and a list of symbols in the dll.

I have written a number of extensions for this including a lisp interpreter (simplisp) which allows the functions to be called from a repl and an event project (graphy_event) which allows some of the functions in lobs to be declared as events. For example, you could hook up construct functions from each of your libs to a construct event and just call the construct event on program start.

Again, this may be a bit heavy for what you are doing but if your interested, I wouldn't mind starting to document it and provide some examples.

**Comment by kaustavdm** [comment]
> In summary there is a modules folder which contains a json file describing the modules, and one folder for each module. Each module has an additional json which contains a dll path (usually just the current folder) and a list of symbols in the dll.

This is _very_ close to what I am trying to implement! Except, for most of my cases the libraries will be expected to expose certain predefined symbols.

> Again, this may be a bit heavy for what you are doing but if your interested, I wouldn't mind starting to document it and provide some examples.

That would be very useful. Being a newcomer to Rust (and systems programming in general), it took me a week to wrap my head around this stuff. More documentation and examples are definitely a big need!

**Comment by kaustavdm** [comment]
Closing this because @tyleo's comments answer my original question.
